#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Hubs,  S3, HTServo,  none,     none,     none)
#pragma config(Sensor, S4,     Accel,               sensorI2CHiTechnicAccel)
#pragma config(Motor,  motorA,          ,              tmotorNormal, openLoop, encoder)
#pragma config(Motor,  motorB,          ,              tmotorNormal, openLoop, encoder)
#pragma config(Motor,  motorC,          ,              tmotorNormal, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     groundGatherer, tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     LeftDrive,     tmotorNormal, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     RightDrive,    tmotorNormal, openLoop, encoder)
#pragma config(Servo,  srvo_S2_C1_1,    Gatherer9,            tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    Gatherer6,            tServoStandard)
#pragma config(Servo,  srvo_S2_C1_3,    Gatherer3,            tServoStandard)
#pragma config(Servo,  srvo_S3_C1_1,    armLeft1,             tServoStandard)
#pragma config(Servo,  srvo_S3_C1_2,    armLeft2,             tServoStandard)
#pragma config(Servo,  srvo_S3_C1_3,    armRight1,            tServoStandard)
#pragma config(Servo,  srvo_S3_C1_4,    armRight2,            tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

double convert(double inches)
{
  //In this part, you convert the inches to encoder rotations and you return that value//
  return (inches* 112);
}


double convertDegree(double Degree)
{
  //In this part, you convert the inches to encoder rotations and you return that value//
  return (Degree* 15.204);
}


//You can use this function to move the robot a set amount of inches with a set speed//
void goInches(int inches, int speed)
{
  //reset the encoders...
  nMotorEncoder[RightDrive] = 0;
  //start up the motors...
  motor[LeftDrive] = speed;
  motor[RightDrive] = speed;
  //you go move until you reach the desired amount of encoder counts...
  while (abs(nMotorEncoder[RightDrive]) < (convert(inches))){ }
  //You stop the motors after the while loop...
  motor[LeftDrive] = 0;
  motor[RightDrive] = 0;
  wait1Msec (500);
}
void goTurn(double Degree, int speed)
{
  //reset the encoders...
  nMotorEncoder[RightDrive] = 0;
  nMotorEncoder[LeftDrive] = 0;
  //start up the motors...
  motor[LeftDrive] = -speed;
  motor[RightDrive] = speed;
  //you go move until you reach the desired amount of encoder counts...
  while ((abs(nMotorEncoder[RightDrive]) < (convertDegree(Degree))) || abs(nMotorEncoder[LeftDrive]) < (convertDegree(Degree))){ }
  //You stop the motors after the while loop...
  motor[LeftDrive] = 0;
  motor[RightDrive] = 0;
  wait1Msec (500);
}



task main()
{
 goInches(70, 50);
}
