#pragma config(Sensor, S1,     MagneticSensor,      sensorHiTechnicMagnetic)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "drivers/HTMAG-driver.h"
task main ()
{
  while (true)
  {
    nxtDisplayTextLine(4, "Mag: %4d", HTMAGreadVal(MagneticSensor));
    wait1Msec(300);
  }

}
