#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Hubs,  S2, HTServo,  HTServo,  none,     none)
#pragma config(Sensor, S3,     touchMux,            sensorHiTechnicTouchMux)
#pragma config(Sensor, S4,     Accel,               sensorI2CHiTechnicAccel)
#pragma config(Motor,  mtr_S1_C1_1,     LeftDrive,     tmotorNormal, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     RightDrive,    tmotorNormal, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     Gatherer,      tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     Lift,          tmotorNormal, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    ArmLeft1,             tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    ArmLeft2,             tServoStandard)
#pragma config(Servo,  srvo_S2_C1_4,    ArmRight1,            tServoStandard)
#pragma config(Servo,  srvo_S2_C1_5,    ArmRight2,            tServoStandard)
#pragma config(Servo,  srvo_S2_C1_6,    Gate,                 tServoStandard)
#pragma config(Servo,  srvo_S2_C2_3,    MagnetBlocker,        tServoStandard)
#pragma config(Servo,  srvo_S2_C2_4,    BackHolder1,          tServoStandard)
#pragma config(Servo,  srvo_S2_C2_5,    BackHolder2,          tServoStandard)
#pragma config(Servo,  srvo_S2_C2_6,    FrontHolder,          tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Tele-Operation Mode Code Template
//
// This file contains a template for simplified creation of an tele-op program for an FTC
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of tele-op mode, you may want to perform some initialization on your robot
// and the variables within your program.
//
// In most cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot()
{
  // Place code here to sinitialize servos to starting positions.
  // Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.
  servo[BackHolder1] = 0; //Bottom
  servo[BackHolder2] = 255; //Bottom
  //servo[BackHolder1] = 120; //Lifted
  //servo[BackHolder2] = 135; //Lifted
  //servo[FrontHolder] = 185; //Push down position
  servo[FrontHolder] = 25; //Reset position
  servo[Gate] = 84; //Reset position
  //servo[Gate] = 97; //Release position
  //servo[MagnetBlocker] = 0; //Down position (Reset here for initialize for autonomous, other for teleop)
  servo[MagnetBlocker] = 140;
  //Basket Up
  //servo[ArmLeft1] = 129;//alays 7 less
  //servo[ArmLeft2] = 134;
  //servo[ArmRight1] = 103;//always 5 less than Right 2
  //servo[ArmRight2] = 108;
  //Basket Down
  /*servo[ArmLeft1] = 152; //always 7 less
  servo[ArmLeft2] = 145;
  servo[ArmRight1] = 103;//always 5 less than Right 2
  servo[ArmRight2] = 108;*/

  servo[ArmLeft1] = 18;//always 7 more
  servo[ArmLeft2] = 11;
  servo[ArmRight1] = 232;//always 5 less than Right 2
  servo[ArmRight2] = 237;

  return;
}


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the tele-op robot operation. Customize as appropriate for
// your specific robot.
//
// Game controller / joystick information is sent periodically (about every 50 milliseconds) from
// the FMS (Field Management System) to the robot. Most tele-op programs will follow the following
// logic:
//   1. Loop forever repeating the following actions:
//   2. Get the latest game controller / joystick settings that have been received from the PC.
//   3. Perform appropriate actions based on the joystick + buttons settings. This is usually a
//      simple action:
//      *  Joystick values are usually directly translated into power levels for a motor or
//         position of a servo.
//      *  Buttons are usually used to start/stop a motor or cause a servo to move to a specific
//         position.
//   4. Repeat the loop.
//
// Your program needs to continuously loop because you need to continuously respond to changes in
// the game controller settings.
//
// At the end of the tele-op period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

task main()
{
  initializeRobot();

  waitForStart();   // wait for start of tele-op phase

  while (true)
  {
	  ///////////////////////////////////////////////////////////
	  ///////////////////////////////////////////////////////////
	  ////                                                   ////
	  ////      Add your robot specific tele-op code here.   ////
	  ////                                                   ////
	  ///////////////////////////////////////////////////////////
	  ///////////////////////////////////////////////////////////

    // Insert code to have servos and motors respond to joystick and button values.

    // Look in the ROBOTC samples folder for programs that may be similar to what you want to perform.
    // You may be able to find "snippets" of code that are similar to the functions that you want to
    // perform.
  }
}
