#pragma config(Sensor, S1,     compass,             sensorI2CHiTechnicCompass)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

  bNxtLCDStatusDisplay = false;

while(1)
{
nxtDisplayStringAt(1,10, "COMPASS: " +SensorValue[S1]);
}


}
