#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     leftMotor,     tmotorTetrix, openLoop, reversed, driveLeft)
#pragma config(Motor,  mtr_S1_C1_2,     rightMotor,    tmotorTetrix, openLoop, driveRight)
//#pragma config(Servo,  srvo_S1_C2_1,     servo1,   tServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#pragma DebuggerWindows("joystickSimple")
void initializeRobot()
{
}
void updateSpeed(){
	getJoystickSettings(joystick);
	float y = -joystick.joy1_y1;
	float x = joystick.joy1_x1;
	//nxtDisplayTextLine(2,"%2.2f",y);
	if(y < 0){
		y = (y / 127) * 100;
		}else{
		y = (y / 128) * 100;
	}
	if(x < 0){
		x = (x / 128) * 100;
		}else{
		x = (x / 127) * 100;
	}
	int leftMotorSpeed = y - x;
	int rightMotorSpeed = y + x;
	if(leftMotorSpeed < -100){
		leftMotorSpeed = -100;
		}else if(leftMotorSpeed > 100){
		leftMotorSpeed = 100;
	}
	if(rightMotorSpeed < -100){
		rightMotorSpeed = -100;
		}else if(rightMotorSpeed > 100){
		rightMotorSpeed = 100;
	}
	motor[leftMotor] = -leftMotorSpeed;
	motor[rightMotor] = -rightMotorSpeed;
}

task main()
{
	initializeRobot();
	waitForStart();
	int threshold = 10;             /* Int 'threshold' will allow us to ignore low       */
	/* readings that keep our robot in perpetual motion. */

	while(true)                            // Infinite loop:
	{
		getJoystickSettings(joystick);
		updateSpeed();

		//if(abs(joystick.joy1_y1) > threshold) {          // Controller 1, right joystick does right motor
		//	motor[leftMotor] = joystick.joy1_y1;
		//	} else {
		//	motor[leftMotor] = 0;
		//}

		//if(abs(joystick.joy1_y2) > threshold) {          // Controller 1, left joystick does left motor
		//	motor[rightMotor] = joystick.joy1_y2;
		//	} else {
		//	motor[rightMotor] = 0;
		//}

		//if(joy1Btn(1))
		//	{
		//		Servo[servo1] = 100;
		// 		motor[leftMotor] = 100;
		//	}
		//	else  if(joy1Btn(2))
		//	{
		//		Servo[servo1]= -100 ;
		// 		motor[rightMotor] = 100;
		//	} else if (joy1Btn(3))
		//	{
		//		Servo[servo1]= 0;
		//		motor[rightMotor] = 100;
		//		motor[leftMotor] = 100;
		//	} else if (joy1Btn(4)){
		//		motor[rightMotor] = 0;
		//		motor[leftMotor] = 0;
		//	}
	}
}
