#pragma config(Hubs,  S1, HTServo,  HTServo,  HTMotor,  HTMotor)
#pragma config(Sensor, S2,     HeightTouch,         sensorTouch)
#pragma config(Sensor, S3,     MagneticSensor,      sensorI2CHiTechnicCompass)
#pragma config(Sensor, S4,     Accel,               sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C3_1,     LeftDrive,     tmotorNormal, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     RightDrive,    tmotorNormal, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_1,     Gatherer,      tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_2,     Lift,          tmotorNormal, openLoop)
#pragma config(Servo,  srvo_S1_C1_1,    ArmLeft1,             tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    ArmLeft2,             tServoStandard)
#pragma config(Servo,  srvo_S1_C1_4,    ArmRight1,            tServoStandard)
#pragma config(Servo,  srvo_S1_C1_5,    ArmRight2,            tServoStandard)
#pragma config(Servo,  srvo_S1_C1_6,    Gate,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C2_1,    TouchServo,           tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    MagnetBlocker,        tServoStandard)
#pragma config(Servo,  srvo_S1_C2_4,    BackHolder1,          tServoStandard)
#pragma config(Servo,  srvo_S1_C2_5,    BackHolder2,          tServoStandard)
#pragma config(Servo,  srvo_S1_C2_6,    FrontHolder,          tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
Port 1: Arm Servos -> Auxiliary Servos -> Drive Motors -> Gatherer Motors
Port 2: Touch Sensor
Port 3: Magnetic Sensor
Port 4: Accelerometer
*/
#include "AutonomousHeaders.h"				 //Include file which has headers such as global variables
#include "JoystickDriver.c"	          //Include file to "handle" the Bluetooth messages.
#include "AutonomousFunctions.c"
#include "accelDriver.h"


///////////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////THESE ARE THE AUTONOMOUS FILES//////////////////////////////
///////////////////////////////////////////////////////////////////////////////////////////
#include "Autonomous Programs\LeftBasket.c"
#include "Autonomous Programs\RightBasket.c"
#include "Autonomous Programs\LeftBasketFar.c"
#include "Autonomous Programs\LeftBasketFarMountain.c"
#include "Autonomous Programs\LeftBasketFarBridge.c"
#include "Autonomous Programs\LeftBasketMountain.c"
#include "Autonomous Programs\RightBasketMountain.c"
#include "Autonomous Programs\LeftMountain.c"
#include "Autonomous Programs\RightMountain.c"
#include "Autonomous Programs\RightCorrigated.c"
#include "Autonomous Programs\RightBasketFar.c"
#include "Autonomous Programs\RightBasketFarMountain.c"
#include "Autonomous Programs\RightBasketFarBridge.c"
#include "Autonomous Programs\DoublerBlock.c"
#include "Autonomous Programs\LeftBridge.c"
#include "Autonomous Programs\RightBridge.c"

///////////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////////////////
#include "Autonomous Programs\getuserinput.c"

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//																		Initialize Robot
//  -Reset the Back Holders
//  -Reset the Front Holder
//  -Close the Basket Gate
//  -Lower the Magnet Blocker
//  -Lower the Basket
/////////////////////////////////////////////////////////////////////////////////////////////////////
void initializeRobot()
{


  servo[BackHolder1] = 128;
  servo[BackHolder2] = 128;
  servo[FrontHolder] = 25; //Reset position
  servo[Gate] = 76; //Reset position
  servo[MagnetBlocker] = 40;
  servo[ArmLeft1] = 245;
  servo[ArmLeft2] = 245;
  servo[ArmRight1] = 10;
  servo[ArmRight2] = 10;
  servo[TouchServo] = 230;
  wait1Msec(500);

  return;
}


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//																				 Main Task
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

task main()
{
  //Arm raises to allow user to see nxt
  servo[ArmLeft1]=0;
  servo[ArmLeft2]=0;
  servo[ArmRight1]=255;
  servo[ArmRight2]=255;
  servo[TouchServo] = 230;
  servo[FrontHolder] = 25;
  servo[Gate] = 76;
  servo[MagnetBlocker] = 120;

  //Clear the screen of the nxt from fcs's control
  eraseDisplay();
  bDisplayDiagnostics = false;
  bNxtLCDStatusDisplay = false;
  wait1Msec(100);
  //Let the user choose the program they want
  ChooseStrategy();
  //Give back control to FCS
  bDisplayDiagnostics = true;
  bNxtLCDStatusDisplay = true;
  wait1Msec(3000);
  //Continue with the regular initialization of the robot
  initializeRobot();

  //Wait for FCS
  waitForStart();


  if (strategy == Balance)
  {
    //if you are balancing, Check the side that the robot is placed on
    if (side == LeftSide)
    {
      //if the robot is on the left side, balance on the left bridge
      LeftBridge();
      StopAllTasks();
    }
    if (side == RightSide)
    {
      //if the robot is on the right side, balance on the right bridge
      RightBridge();
      StopAllTasks();
    }
  }
  if (strategy == Block)
  {
    if (Block == DoublerBlock)
    {
      BlockDoubler();
    }
  }
  if (strategy == Score)
  {
    if (side == LeftSide)
    {
      if (goal == ScoreAndCross)
      {
        LeftBasketMountain();
        StopAllTasks();
      }
      if (goal == preloadDump)
      {
        LeftBasket();
        StopAllTasks();
      }
      if (goal == Cross)
      {
        LeftMountain();
      }
      if (goal == Corrigated)
      {
        RightCorrigated();
      }
      if (goal == FarDump)
      {

        LeftBasketFar();
        StopAllTasks();
      }
      if (goal == FarDumpMountain)
      {
        LeftBasketFarMountain();
        StopAllTasks();
      }
      if (goal == FarDumpBridge)
      {
        LeftBasketFarBridge();
        StopAllTasks();
      }
    }
    if (side == RightSide)
    {
      //Check what type of scoring you have
      if (goal == ScoreAndCross)
      {
        RightBasketMountain();
        StopAllTasks();
      }
      if (goal == preloadDump)
      {
        RightBasket();
        StopAllTasks();
      }
      if (goal == Cross)
      {
        RightMountain();
        StopAllTasks();
      }
      if (goal == FarDumpMountain)
      {
        RightBasketFarMountain();
        StopAllTasks();
      }
      if (goal == FarDump)
      {
        RightBasketFar();
        StopAllTasks();
      }
       if (goal == FarDumpBridge)
      {
        RightBasketFarBridge();
        StopAllTasks();
      }

    }
  }
}
