#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Hubs,  S3, HTServo,  none,     none,     none)
#pragma config(Sensor, S4,     Accel,               sensorI2CHiTechnicAccel)
#pragma config(Motor,  motorA,          ,              tmotorNormal, openLoop, encoder)
#pragma config(Motor,  motorB,          ,              tmotorNormal, openLoop, encoder)
#pragma config(Motor,  motorC,          ,              tmotorNormal, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     groundGatherer, tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     LeftDrive,     tmotorNormal, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     RightDrive,    tmotorNormal, openLoop, encoder)
#pragma config(Servo,  srvo_S2_C1_1,    Gatherer9,            tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    Gatherer6,            tServoStandard)
#pragma config(Servo,  srvo_S2_C1_3,    Gatherer3,            tServoStandard)
#pragma config(Servo,  srvo_S3_C1_1,    armLeft1,             tServoStandard)
#pragma config(Servo,  srvo_S3_C1_2,    armLeft2,             tServoStandard)
#pragma config(Servo,  srvo_S3_C1_3,    armRight1,            tServoStandard)
#pragma config(Servo,  srvo_S3_C1_4,    armRight2,            tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
 goInches(54, speed);
 goTurn(90,speed);
 goInches(200,speed);
}
