#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Hubs,  S2, HTMotor,  none,     none,     none)	// AMM: Nothing plugged into Sensor 2 on NXT.
#pragma config(Hubs,  S3, HTMotor,  none,     none,     none)	// AMM: Nothing plugged into Sensor 3 on NXT.
#pragma config(Hubs,  S4, HTMotor,  none,     none,     none)	// AMM: Nothing plugged into Sensor 4 on NXT.
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)	// AMM: Nothing plugged into Sensor 2 on NXT.
#pragma config(Sensor, S3,     ,               sensorI2CMuxController)	// AMM: Nothing plugged into Sensor 3 on NXT.
#pragma config(Sensor, S4,     ,               sensorI2CMuxController)	// AMM: Nothing plugged into Sensor 4 on NXT.
#pragma config(Motor,  mtr_S1_C1_1,     leftMotor,     tmotorTetrix, openLoop, reversed, driveLeft)
#pragma config(Motor,  mtr_S1_C1_2,     rightMotor,    tmotorTetrix, openLoop, driveRight)
#pragma config(Motor,  mtr_S2_C1_1,     spinnyThingIn, tmotorTetrix, openLoop)	// AMM: Nothing plugged into Sensor 2 on NXT.
#pragma config(Motor,  mtr_S2_C1_2,     spinnyThingUp, tmotorTetrix, openLoop)	// AMM: Nothing plugged into Sensor 2 on NXT.
#pragma config(Motor,  mtr_S3_C1_1,     motorH,        tmotorTetrix, openLoop)	// AMM: Nothing plugged into Sensor 3 on NXT.
#pragma config(Motor,  mtr_S3_C1_2,     motorI,        tmotorTetrix, openLoop)	// AMM: Nothing plugged into Sensor 3 on NXT.
#pragma config(Motor,  mtr_S4_C1_1,     motorJ,        tmotorTetrix, openLoop)	// AMM: Nothing plugged into Sensor 4 on NXT.
#pragma config(Motor,  mtr_S4_C1_2,     motorK,        tmotorTetrix, openLoop)	// AMM: Nothing plugged into Sensor 4 on NXT.
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Tele-Operation Mode Code Template
//
// This file contains a template for simplified creation of an tele-op program for an FTC
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of tele-op mode, you may want to perform some initialization on your robot
// and the variables within your program.
//
// In most cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot()
{
	// Place code here to sinitialize servos to starting positions.
	// Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.

	return;
}


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the tele-op robot operation. Customize as appropriate for
// your specific robot.
//
// Game controller / joystick information is sent periodically (about every 50 milliseconds) from
// the FMS (Field Management System) to the robot. Most tele-op programs will follow the following
// logic:
//   1. Loop forever repeating the following actions:
//   2. Get the latest game controller / joystick settings that have been received from the PC.
//   3. Perform appropriate actions based on the joystick + buttons settings. This is usually a
//      simple action:
//      *  Joystick values are usually directly translated into power levels for a motor or
//         position of a servo.
//      *  Buttons are usually used to start/stop a motor or cause a servo to move to a specific
//         position.
//   4. Repeat the loop.
//
// Your program needs to continuously loop because you need to continuously respond to changes in
// the game controller settings.
//
// At the end of the tele-op period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////
void updateSpeed(){
		getJoystickSettings(joystick);
		int y = -joystick.joy1_y1;
		int x = joystick.joy1_x1;
		//nxtDisplayTextLine(2,"%2.2f",y);
		if(y < 0){
			y = (y / 127) * 100;
		}else{
			y = (y / 128) * 100;
		}
		if(x < 0){
			x = (x / 128) * 100;
		}else{
			x = (x / 127) * 100;
		}
		int leftMotorSpeed = y - x;
		int rightMotorSpeed = y + x;
		if(leftMotorSpeed < -100){
			leftMotorSpeed = -100;
		}else if(leftMotorSpeed > 100){
			leftMotorSpeed = 100;
		}
		if(rightMotorSpeed < -100){
			rightMotorSpeed = -100;
		}else if(rightMotorSpeed > 100){
			rightMotorSpeed = 100;
		}
		motor[leftMotor] = leftMotorSpeed;
		motor[rightMotor] = rightMotorSpeed;
}

task main()
{
	initializeRobot();

	waitForStart();   // wait for start of tele-op phase

	bool lastSpinnyUp = false;
	bool currentSpinnyUp = false;
	bool spinnyThingInRun = false;
	while (true)
	{
		updateSpeed();
		if(joy1Btn(Btn1)){
			lastSpinnyUp = currentSpinnyUp;
			currentSpinnyUp = true;
		}else{
			lastSpinnyUp = currentSpinnyUp;
			currentSpinnyUp = false;
		}
		if(lastSpinnyUp == false && currentSpinnyUp == true){
			motor[spinnyThingUp] = 100;
		}else if(lastSpinnyUp == true && currentSpinnyUp == false){
			motor[spinnyThingUp] = 0;
		}
		if(joy1Btn(Btn2) && spinnyThingInRun == false){
			spinnyThingInRun = true;
			motor[spinnyThingIn] = 100;
		}else if(joy1Btn(Btn2) && spinnyThingInRun == true){
			spinnyThingInRun = false;
			motor[spinnyThingIn] = 0;
		}

		///////////////////////////////////////////////////////////
		///////////////////////////////////////////////////////////
		////                                                   ////
		////      Add your robot specific tele-op code here.   ////
		////                                                   ////
		///////////////////////////////////////////////////////////
		///////////////////////////////////////////////////////////

		// Insert code to have servos and motors respond to joystick and button values.
		// Look in the ROBOTC samples folder for programs that may be similar to what you want to perform.
		// You may be able to find "snippets" of code that are similar to the functions that you want to
		// perform.
	}
}
