#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     leftMotor,     tmotorTetrix, openLoop, reversed, driveLeft)
#pragma config(Motor,  mtr_S1_C1_2,     rightMotor,    tmotorTetrix, openLoop, driveRight)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#pragma DebuggerWindows("joystickSimple")
void initializeRobot()
{
	servo[servo1]=0;
}

task main()
{
	initializeRobot();
	waitForStart();
	int threshold = 10;             /* Int 'threshold' will allow us to ignore low       */
	/* readings that keep our robot in perpetual motion. */

	while(true)                            // Infinite loop:
	{
		getJoystickSettings(joystick);

		if(abs(joystick.joy1_y2) > threshold) {          // Controller 1, right joystick does right motor
			motor[leftMotor] = joystick.joy1_y2;
			} else {
			motor[leftMotor] = 0;
		}

		if(abs(joystick.joy1_y1) > threshold) {          // Controller 1, left joystick does left motor
			motor[rightMotor] = joystick.joy1_y1;
			} else {
			motor[rightMotor] = 0;
		}

		if(joystick.joy1_Buttons == 1)// if Button 6 is pressed on joy1:
		{
			servo[servo1] = 100 ;             // motorA is run at a power level of 50
		}
		else       // motorA is run at a power level of 50
		{
			servo[servo1]= 0 ;
		}
	}
}
