#pragma config(Hubs,  S1, HTServo,  HTServo,  HTMotor,  HTMotor)
#pragma config(Sensor, S2,     HeightTouch,         sensorTouch)
#pragma config(Sensor, S3,     MagneticSensor,      sensorI2CHiTechnicCompass)
#pragma config(Sensor, S4,     Accel,               sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C3_1,     LeftDrive,     tmotorNormal, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     RightDrive,    tmotorNormal, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_1,     Gatherer,      tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_2,     Lift,          tmotorNormal, openLoop)
#pragma config(Servo,  srvo_S1_C1_1,    ArmLeft1,             tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    ArmLeft2,             tServoStandard)
#pragma config(Servo,  srvo_S1_C1_4,    ArmRight1,            tServoStandard)
#pragma config(Servo,  srvo_S1_C1_5,    ArmRight2,            tServoStandard)
#pragma config(Servo,  srvo_S1_C1_6,    Gate,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C2_1,    TouchServo,           tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    MagnetBlocker,        tServoStandard)
#pragma config(Servo,  srvo_S1_C2_4,    BackHolder1,          tServoStandard)
#pragma config(Servo,  srvo_S1_C2_5,    BackHolder2,          tServoStandard)
#pragma config(Servo,  srvo_S1_C2_6,    FrontHolder,          tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

double convert(double inches)
{
  //In this part, you convert the inches to encoder rotations and you return that value//
  return (inches* 112);
}


double convertDegree(double Degree)
{
  //In this part, you convert the inches to encoder rotations and you return that value//
  return (Degree* 16.1854);
}


//You can use this function to move the robot a set amount of inches with a set speed//
void goInches(int inches, int speed)
{
  //reset the encoders...
  nMotorEncoder[RightDrive] = 0;
  //start up the motors...
  motor[LeftDrive] = speed;
  motor[RightDrive] = speed;
  //you go move until you reach the desired amount of encoder counts...
  while (abs(nMotorEncoder[RightDrive]) < (convert(inches))){ }
  //You stop the motors after the while loop...
  motor[LeftDrive] = 0;
  motor[RightDrive] = 0;
  wait1Msec (500);
}
void goTurn(double Degree, int speed)
{
  //reset the encoders...
  nMotorEncoder[RightDrive] = 0;
  nMotorEncoder[LeftDrive] = 0;
  wait1Msec(300);
  //start up the motors...
  motor[LeftDrive] = -speed;
  motor[RightDrive] = speed;
  //you go move until you reach the desired amount of encoder counts...
  while ((abs(nMotorEncoder[RightDrive]) < (convertDegree(Degree))) || abs(nMotorEncoder[LeftDrive]) < (convertDegree(Degree))){ }
  //You stop the motors after the while loop...
  motor[LeftDrive] = 0;
  motor[RightDrive] = 0;
  wait1Msec (500);
}



task main()
{
 goTurn(720, 50);
}
