#pragma config(Sensor, S1,     Light,               sensorLightInactive)
#pragma config(Sensor, S2,     sonar,               sensorSONAR)
#pragma config(Sensor, S3,     Accel,               sensorI2CHiTechnicAccel)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
eraseDisplay();

  bNxtLCDStatusDisplay = false;
  wait1Msec(100);
  while(1)
  {

    if (SensorValue[S2]< 667)
SensorType[S1] = sensorLightActive;
    else
SensorType[S1] = sensorLightInactive;
//wait1Msec(1000);
//wait1Msec(1000);

nxtDisplayStringAt(1,15,"Sonar: "+ SensorValue[S2]);

}
}
